//! Turns `diagnostic-codes.tsv` into the table `registry.rs` includes.
//!
//! The table is validated here rather than at a lookup: a row with no tab, an
//! unknown prefix, an empty summary, or a code out of order stops the build
//! with the row that caused it. Nothing downstream then has a reason to panic.

use std::fmt;
use std::fs;
use std::path::PathBuf;

/// The families the table admits, longest prefix first so `KSLP` wins over a
/// shorter prefix that also matches.
///
/// Paired with `CodeFamily` in `registry.rs`; a variant renamed on one side
/// stops the build on the other, because the generated table names it.
const FAMILIES: [(&str, &str); 13] = [
    ("KLINT", "Lint"),
    ("KSLP", "ShaderParser"),
    ("KSLS", "ShaderSemantics"),
    ("KLEX", "Lexer"),
    ("KPAR", "Parser"),
    ("KMAC", "Macro"),
    ("KSEM", "Semantics"),
    ("KPK", "Package"),
    ("KTC", "Toolchain"),
    ("KCL", "Cli"),
    ("KIC", "Internal"),
    ("KIR", "Lowering"),
    ("KBE", "Backend"),
];

/// The order rows must run in, matching `registry::FAMILIES`.
const FAMILY_ORDER: [&str; 13] = [
    "Lexer",
    "Parser",
    "Macro",
    "Semantics",
    "Lowering",
    "Backend",
    "ShaderParser",
    "ShaderSemantics",
    "Package",
    "Toolchain",
    "Cli",
    "Lint",
    "Internal",
];

/// What can be wrong with the table.
#[derive(Debug)]
enum TableError {
    /// The table could not be read.
    Unreadable(String),
    /// The generated table could not be written.
    Unwritable(String),
    /// A row is malformed, named by line number.
    Row(usize, String),
}

impl fmt::Display for TableError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TableError::Unreadable(reason) => {
                write!(f, "diagnostic-codes.tsv could not be read: {reason}")
            }
            TableError::Unwritable(reason) => {
                write!(f, "the generated code table could not be written: {reason}")
            }
            TableError::Row(line, reason) => {
                write!(f, "diagnostic-codes.tsv line {line}: {reason}")
            }
        }
    }
}

fn main() {
    println!("cargo::rerun-if-changed=diagnostic-codes.tsv");
    println!("cargo::rerun-if-changed=build.rs");
    if let Err(error) = generate() {
        println!("cargo::error={error}");
        std::process::exit(1);
    }
}

/// Reads the table and writes the Rust table it becomes.
fn generate() -> Result<(), TableError> {
    let manifest = PathBuf::from(env_or_default("CARGO_MANIFEST_DIR", "."));
    let table = fs::read_to_string(manifest.join("diagnostic-codes.tsv"))
        .map_err(|error| TableError::Unreadable(error.to_string()))?;

    let mut rendered = String::from(
        "/// The table `diagnostic-codes.tsv` declares, generated by `build.rs`.\nstatic CODES: [RegisteredCode; ",
    );
    let mut rows = String::new();
    let mut count = 0usize;
    let mut previous = (0usize, 0u32);

    for (index, line) in table.lines().enumerate() {
        let number = index + 1;
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((code, summary)) = line.split_once('\t') else {
            return Err(TableError::Row(
                number,
                "no tab between the code and its summary".to_owned(),
            ));
        };
        if summary.trim().is_empty() {
            return Err(TableError::Row(number, format!("{code} has no summary")));
        }
        if summary.contains('\t') {
            return Err(TableError::Row(
                number,
                format!("{code} has more than one tab"),
            ));
        }
        let (family, digits) = classify(code)
            .ok_or_else(|| TableError::Row(number, format!("`{code}` is not a code")))?;
        let position = FAMILY_ORDER
            .iter()
            .position(|candidate| *candidate == family)
            .ok_or_else(|| TableError::Row(number, format!("`{family}` has no order")))?;
        let current = (position, digits);
        if current <= previous {
            return Err(TableError::Row(
                number,
                format!("{code} does not follow the row before it in family and number order"),
            ));
        }
        previous = current;
        count += 1;
        rows.push_str(&format!(
            "    RegisteredCode {{ code: {}, summary: {}, family: CodeFamily::{family} }},\n",
            quote(code),
            quote(summary)
        ));
    }

    if count == 0 {
        return Err(TableError::Unreadable("the table is empty".to_owned()));
    }

    rendered.push_str(&count.to_string());
    rendered.push_str("] = [\n");
    rendered.push_str(&rows);
    rendered.push_str("];\n");

    let out = PathBuf::from(env_or_default("OUT_DIR", ".")).join("diagnostic_codes.rs");
    fs::write(out, rendered).map_err(|error| TableError::Unwritable(error.to_string()))
}

/// The family name and number a code carries, or `None` when it is not a code.
fn classify(code: &str) -> Option<(&'static str, u32)> {
    for (prefix, family) in FAMILIES {
        let Some(digits) = code.strip_prefix(prefix) else {
            continue;
        };
        if digits.is_empty() || !digits.bytes().all(|byte| byte.is_ascii_digit()) {
            continue;
        }
        return digits.parse().ok().map(|number| (family, number));
    }
    None
}

/// `text` as a Rust string literal.
fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for character in text.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

/// An environment variable cargo sets, or `fallback` when it is absent.
fn env_or_default(name: &str, fallback: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| fallback.to_owned())
}
