//! The generated crate's `Cargo.toml` and `README.md`.
//!
//! # Why the dependencies are paths
//!
//! `kira-main` and the crates under it are not published yet, so the generated
//! manifest points at the toolchain checkout that produced it. That is the whole
//! reason the crate is regenerated rather than committed: the paths are true of
//! one machine, and a committed manifest carrying them would be wrong on every
//! other one. When the runtime crates publish, this becomes a version
//! requirement and the crate becomes committable — the README says so, in the
//! generated crate, where the person who would otherwise commit it is reading.

use crate::wrapper::WrapperSpec;
use crate::wrapper::render::Model;

/// Renders the generated crate's `Cargo.toml`.
pub(crate) fn cargo_toml(spec: &WrapperSpec<'_>, model: &Model) -> String {
    let root = model_root(spec);
    format!(
        "# Generated by `kirac build` from the Kira library `{library}`.\n\
         #\n\
         # Do not edit. Every build of the library rewrites it, and the dependency\n\
         # paths below are true of the toolchain checkout that generated it.\n\
         \n\
         # Its own workspace root, deliberately. The crate is written under the\n\
         # library's `.kira-build/`, which may sit inside a cargo workspace that\n\
         # knows nothing about it — and cargo refuses a manifest that is inside a\n\
         # workspace directory without being one of its members.\n\
         [workspace]\n\
         \n\
         [package]\n\
         name = \"{library}\"\n\
         version = \"{version}\"\n\
         edition = \"2024\"\n\
         # Path dependencies cannot be published, and this crate is a build\n\
         # artifact rather than something to release.\n\
         publish = false\n\
         \n\
         [dependencies]\n\
         kira-bytecode = {{ path = \"{root}/crates/kira-bytecode\" }}\n\
         kira-main = {{ path = \"{root}/crates/kira-main\" }}\n\
         kira-runtime-abi = {{ path = \"{root}/crates/kira-runtime-abi\" }}\n\
         \n\
         # Generated code is code: it is held to the same bar as the compiler that\n\
         # wrote it, so that a consumer's own lint gate never fails on a file they\n\
         # did not write. `missing_docs` is deliberately not enabled: every item in\n\
         # `src/lib.rs` carries a doc comment, but the crate root cannot — an inner\n\
         # doc comment would stop the file being `include!`able, which is what lets\n\
         # a consumer's `build.rs` generate the wrapper into `OUT_DIR`. This\n\
         # README is the crate's documentation.\n\
         [lints.rust]\n\
         unsafe_code = \"forbid\"\n",
        library = model.library,
        version = spec.version,
        root = root,
    )
}

/// The toolchain root, escaped for a TOML basic string.
fn model_root(spec: &WrapperSpec<'_>) -> String {
    spec.toolchain_root
        .display()
        .to_string()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}

/// Renders the generated crate's `README.md`.
pub(crate) fn readme(model: &Model) -> String {
    let mut out = format!(
        "# {library}\n\
         \n\
         Generated by `kirac build` from the Kira library `{library}`. **Do not\n\
         edit, and do not commit**: every build of the library rewrites this\n\
         directory, and the dependency paths in `Cargo.toml` are true only of the\n\
         Kira checkout that produced it.\n\
         \n\
         ## What this is\n\
         \n\
         The library compiled for the **VM engine**. `{library}.kbc` is embedded in\n\
         `src/lib.rs` with `include_bytes!` and runs on the Kira VM inside your\n\
         process. There is no linker step, no LLVM, and no `unsafe` anywhere in the\n\
         generated code — this crate builds anywhere Rust builds, including\n\
         `wasm32-unknown-unknown`.\n\
         \n\
         ## Using it\n\
         \n\
         ```toml\n\
         [dependencies]\n\
         {library} = {{ path = \"../{library}/.kira-build/rust/{library}\" }}\n\
         ```\n\
         \n\
         ```rust,ignore\n\
         let library = {ty}::load()?;\n\
         ```\n\
         \n\
         `load` checks the embedded bytecode against the surface this crate was\n\
         generated from and names the first export that disagrees, so a stale\n\
         wrapper fails at load rather than by calling the wrong function.\n\
         \n\
         ### Where the library's output goes\n\
         \n\
         `load()` sends the library's `print` to this process's stdout. To send it\n\
         somewhere else — a log, a test buffer, a browser console — supply a host:\n\
         \n\
         ```rust,ignore\n\
         let library = {ty}::load_with(my_host)?;\n\
         library.with_host(|host| /* read what it collected */);\n\
         ```\n\
         \n\
         A host is anything implementing `kira_runtime_abi::HostCapabilities`;\n\
         `CapturingHost` in that crate records every line and is what the tests use.\n\
         `{ty}` and each handle type are generic over it, defaulting to\n\
         `StdoutHost`, so nothing needs a type annotation until you supply one.\n\
         \n\
         ## What it promises\n\
         \n\
         - **One thread.** `{ty}` is neither `Send` nor `Sync`. One instance belongs\n\
           to one thread.\n\
         - **Handles are owned.** A value of an exported class type names a live\n\
           object inside the library. Dropping it releases that object, and nothing\n\
           else does.\n\
         - **Arguments are lent, results are owned.** A `&str` argument is copied\n\
           into the library for the call; a `String` result is yours.\n\
         \n",
        library = model.library,
        ty = model.library_type,
    );

    out.push_str("## The surface\n\n");
    if model.functions.is_empty() {
        out.push_str("This library exports no functions.\n");
    } else {
        out.push_str("| Kira | Rust |\n|---|---|\n");
        for function in &model.functions {
            out.push_str(&format!(
                "| `{}` | `{}::{}` |\n",
                function.kira_name, model.library_type, function.method
            ));
        }
    }
    if !model.classes.is_empty() {
        out.push_str("\nExported classes, each a Rust newtype over a handle: ");
        let names: Vec<String> = model
            .classes
            .iter()
            .map(|class| format!("`{}`", class.rust))
            .collect();
        out.push_str(&names.join(", "));
        out.push_str(".\n");
    }
    out
}
