//! The generated crate's `Cargo.toml` and `README.md`.
//!
//! # Why the dependencies are paths
//!
//! `kira-main` and the crates under it are not published yet, so the generated
//! manifest points at the toolchain checkout that produced it. That is the whole
//! reason the crate is regenerated rather than committed: the paths are true of
//! one machine, and a committed manifest carrying them would be wrong on every
//! other one. When the runtime crates publish, this becomes a version
//! requirement and the crate becomes committable — the README says so, in the
//! generated crate, where the person who would otherwise commit it is reading.

use crate::wrapper::WrapperSpec;
use crate::wrapper::render::{EngineBinding, Model};

/// The `kirac` invocation that produced a crate, for its generated header.
fn built_by(engine: &EngineBinding) -> &'static str {
    match engine {
        EngineBinding::Vm => "`kirac build`",
        EngineBinding::Hybrid { .. } => "`kirac build --backend hybrid`",
    }
}

/// The `[dependencies]` block a generated crate needs for its engine.
///
/// The hybrid engine's crate depends on `kira-hybrid-main` where the VM
/// engine's depends on `kira-main`, and that one line is where `libloading`
/// enters a consumer's dependency graph. It is a real cost of this engine and
/// the generated README says so, rather than it arriving unannounced in a
/// `cargo tree`.
fn dependencies(engine: &EngineBinding, root: &str) -> String {
    match engine {
        EngineBinding::Vm => format!(
            "kira-bytecode = {{ path = \"{root}/crates/kira-bytecode\" }}\n\
             kira-main = {{ path = \"{root}/crates/kira-main\" }}\n\
             kira-runtime-abi = {{ path = \"{root}/crates/kira-runtime-abi\" }}\n"
        ),
        EngineBinding::Hybrid { .. } => format!(
            "kira-bytecode = {{ path = \"{root}/crates/kira-bytecode\" }}\n\
             # The hybrid engine's embedding surface. It pulls in `libloading`,\n\
             # because the native half is a shared library this process opens at\n\
             # load; the VM engine needs no such thing, which is why it stays the\n\
             # default.\n\
             kira-hybrid-main = {{ path = \"{root}/crates/kira-hybrid-main\" }}\n\
             kira-runtime-abi = {{ path = \"{root}/crates/kira-runtime-abi\" }}\n"
        ),
    }
}

/// Renders the generated crate's `Cargo.toml`, for either VM-family engine.
pub(crate) fn cargo_toml(spec: &WrapperSpec<'_>, model: &Model) -> String {
    let root = model_root(spec);
    let dependencies = dependencies(&model.engine, &root);
    let built_by = built_by(&model.engine);
    format!(
        "# Generated by {built_by} from the Kira library `{library}`.\n\
         #\n\
         # Do not edit. Every build of the library rewrites it, and the dependency\n\
         # paths below are true of the toolchain checkout that generated it.\n\
         \n\
         # Its own workspace root, deliberately. The crate is written under the\n\
         # library's `.kira-build/`, which may sit inside a cargo workspace that\n\
         # knows nothing about it — and cargo refuses a manifest that is inside a\n\
         # workspace directory without being one of its members.\n\
         [workspace]\n\
         \n\
         [package]\n\
         name = \"{library}\"\n\
         version = \"{version}\"\n\
         edition = \"2024\"\n\
         # Path dependencies cannot be published, and this crate is a build\n\
         # artifact rather than something to release.\n\
         publish = false\n\
         # Stated rather than left to cargo's auto-detection. The native engine\n\
         # writes a `build.rs` into this same directory, and the library build\n\
         # deletes it when it switches back to the VM — but cargo decides whether\n\
         # to run a build script by looking for the file, so saying `false` here\n\
         # is what makes \"this engine has no build script\" a fact of the manifest\n\
         # rather than a fact about what happens to be on disk.\n\
         build = false\n\
         \n\
         [dependencies]\n\
         {dependencies}\
         \n\
         # Generated code is code: it is held to the same bar as the compiler that\n\
         # wrote it, so that a consumer's own lint gate never fails on a file they\n\
         # did not write. `missing_docs` is deliberately not enabled: every item in\n\
         # `src/lib.rs` carries a doc comment, but the crate root cannot — an inner\n\
         # doc comment would stop the file being `include!`able, which is what lets\n\
         # a consumer's `build.rs` generate the wrapper into `OUT_DIR`. This\n\
         # README is the crate's documentation.\n\
         [lints.rust]\n\
         unsafe_code = \"forbid\"\n",
        library = model.library,
        version = spec.version,
    )
}

/// Renders the native-engine crate's `Cargo.toml`.
///
/// Two differences from the VM engine's, and both are forced. It has a
/// `build.rs`, because something has to point the linker at the archive. And it
/// cannot forbid `unsafe`: calling a C symbol is `unsafe` by definition, so the
/// lints deny what can still be denied — an `unsafe` operation hiding inside an
/// `unsafe fn`'s body, where no block marks it.
pub(crate) fn native_cargo_toml(
    spec: &crate::wrapper::NativeWrapperSpec<'_>,
    model: &crate::wrapper::render_native::NativeModel,
) -> String {
    let root = escape(spec.toolchain_root);
    format!(
        "# Generated by `kirac build --backend llvm` from the Kira library\n\
         # `{library}`.\n\
         #\n\
         # Do not edit. Every build of the library rewrites it, and the dependency\n\
         # paths below are true of the toolchain checkout that generated it.\n\
         \n\
         # Its own workspace root, deliberately. The crate is written under the\n\
         # library's `.kira-build/`, which may sit inside a cargo workspace that\n\
         # knows nothing about it — and cargo refuses a manifest that is inside a\n\
         # workspace directory without being one of its members.\n\
         [workspace]\n\
         \n\
         [package]\n\
         name = \"{library}\"\n\
         version = \"{version}\"\n\
         edition = \"2024\"\n\
         # Path dependencies cannot be published, and this crate is a build\n\
         # artifact rather than something to release.\n\
         publish = false\n\
         # Points the linker at the static archive beside the library.\n\
         build = \"build.rs\"\n\
         \n\
         [dependencies]\n\
         # `kira-main` is here for its error type alone: a consumer's `match` on a\n\
         # failure reads identically against either engine.\n\
         kira-main = {{ path = \"{root}/crates/kira-main\" }}\n\
         kira-runtime-abi = {{ path = \"{root}/crates/kira-runtime-abi\" }}\n\
         \n\
         # Generated code is code. `unsafe_code` cannot be forbidden here — calling\n\
         # a C symbol is unsafe by definition — so what is denied instead is the\n\
         # thing that would let it hide: an unsafe operation inside an `unsafe fn`\n\
         # with no block marking it.\n\
         [lints.rust]\n\
         unsafe_op_in_unsafe_fn = \"deny\"\n",
        library = model.library,
        version = spec.version,
        root = root,
    )
}

/// Renders the native-engine crate's `README.md`.
pub(crate) fn native_readme(model: &crate::wrapper::render_native::NativeModel) -> String {
    let mut out = format!(
        "# {library}\n\
         \n\
         Generated by `kirac build --backend llvm` from the Kira library\n\
         `{library}`. **Do not edit, and do not commit**: every build of the library\n\
         rewrites this directory, and the paths in `Cargo.toml` and `build.rs` are\n\
         true only of the machine that produced it.\n\
         \n\
         ## What this is\n\
         \n\
         The library compiled for the **native engine**: real machine code in\n\
         `lib{library}.a`, which `build.rs` links into your binary. The archive is\n\
         self-contained — it carries the Kira native runtime's members too — so\n\
         there is one `-l` and no arrangement with the Kira toolchain.\n\
         \n\
         **Your build needs no LLVM.** LLVM compiled the library; linking an\n\
         archive does not.\n\
         \n\
         ## Using it\n\
         \n\
         ```toml\n\
         [dependencies]\n\
         {library} = {{ path = \"../{library}/.kira-build/rust/{library}\" }}\n\
         ```\n\
         \n\
         ```rust,ignore\n\
         let library = {ty}::load()?;\n\
         ```\n\
         \n\
         The consumer's code is identical to the VM engine's. `load()` references\n\
         the library's ABI marker, so a stale archive fails your **link**, naming\n\
         the marker, rather than calling the wrong code at run time.\n\
         \n\
         ## What it promises\n\
         \n\
         - **One thread.** `{ty}` is neither `Send` nor `Sync`.\n\
         - **Handles are owned.** A value of an exported class type names a live\n\
           object inside the library. Dropping it calls the library's destructor,\n\
           and nothing else does.\n\
           \n\
         - **Arguments are lent, results are owned.** A `&str` argument is copied\n\
           into the library for the call; a `String` result is yours, and the\n\
           library's own copy is freed before the call returns.\n\
         \n\
         ## What differs from the VM engine\n\
         \n\
         - **`print` goes to this process's stdout**, and nothing redirects it. The\n\
           VM engine takes a host (`load_with`); native code calls the runtime's\n\
           printer directly, and giving it a host would be an ABI, not a\n\
           parameter.\n\
         - **A Kira trap ends the process**, exactly as a `kira build` binary does.\n\
           Use `attempt`/`try`/`handle` inside the library to keep a trap away from\n\
           the boundary — that is the portable answer, and it works on both\n\
           engines.\n\
         - **One Kira native library per binary.** Two of them both define the\n\
           `kira_rt_*` runtime, so linking two fails with a duplicate-symbol error\n\
           — loud, at link, by name. That is the v1 answer *because* it cannot be\n\
           missed; the fix is per-library runtime prefixing (`kira_rt_*` becoming\n\
           `kira_rt_<library>_*`), at which point two archives stop naming the same\n\
           symbols. A host that `dlopen`s the shared form instead is already\n\
           isolated by `RTLD_LOCAL`.\n\
         \n",
        library = model.library,
        ty = model.library_type,
    );

    out.push_str("## The surface\n\n");
    if model.functions.is_empty() {
        out.push_str("This library exports no functions.\n");
    } else {
        out.push_str("| Kira | Rust | Symbol |\n|---|---|---|\n");
        for (function, symbol) in &model.functions {
            out.push_str(&format!(
                "| `{}` | `{}::{}` | `{}` |\n",
                function.kira_name, model.library_type, function.method, symbol,
            ));
        }
    }
    if !model.classes.is_empty() {
        out.push_str("\nExported classes, each a Rust newtype over a handle: ");
        let names: Vec<String> = model
            .classes
            .iter()
            .map(|(class, _)| format!("`{}`", class.rust))
            .collect();
        out.push_str(&names.join(", "));
        out.push_str(".\n");
    }
    out
}

/// A path, escaped for a TOML basic string.
fn escape(path: &std::path::Path) -> String {
    path.display()
        .to_string()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}

/// The toolchain root, escaped for a TOML basic string.
fn model_root(spec: &WrapperSpec<'_>) -> String {
    escape(spec.toolchain_root)
}

/// What this crate *is*, in the README, for the engine it was generated for.
///
/// The hybrid engine's section is the longest of the three and deliberately so:
/// it is the only engine whose artifact is not entirely inside the consumer's
/// binary, so it is the only one with a deployment question — and the place to
/// answer that is the README in the crate the consumer depends on, not a design
/// note in the compiler's repository.
fn what_this_is(model: &Model) -> String {
    match &model.engine {
        EngineBinding::Vm => format!(
            "## What this is\n\
             \n\
             The library compiled for the **VM engine**. `{library}.kbc` is embedded in\n\
             `src/lib.rs` with `include_bytes!` and runs on the Kira VM inside your\n\
             process. There is no linker step, no LLVM, and no `unsafe` anywhere in the\n\
             generated code — this crate builds anywhere Rust builds, including\n\
             `wasm32-unknown-unknown`.\n",
            library = model.library,
        ),
        EngineBinding::Hybrid { native_half, .. } => format!(
            "## What this is\n\
             \n\
             The library compiled for the **hybrid engine**: the one engine that honors\n\
             the library's own `@Runtime`/`@Native` annotations. Every `@Runtime`\n\
             function runs as bytecode on the Kira VM in your process; every `@Native`\n\
             one runs as machine code in a shared library. The VM engine compiles all of\n\
             it to bytecode and the native engine compiles all of it to machine code —\n\
             neither is wrong, and neither lets the library's author choose per\n\
             function.\n\
             \n\
             **Your build needs no LLVM.** LLVM compiled the native half; loading a\n\
             shared library does not.\n\
             \n\
             ### Deploying it: one file\n\
             \n\
             Two of the three artifacts are embedded in this crate — `{library}.kbc` and\n\
             `{library}.khm`, the bytecode and the split that describes it. The third is\n\
             not, and cannot be: it is a shared library your process opens at run time.\n\
             \n\
             So shipping this program means shipping **one extra file**:\n\
             \n\
             ```text\n\
             {native_file}\n\
             ```\n\
             \n\
             Set **`{variable}`** and that path is the whole answer: `load()` uses it\n\
             or fails naming it, and never quietly falls back to another copy.\n\
             \n\
             With no override, `load()` takes the first of these that exists:\n\
             \n\
             1. **Beside your own executable** — the shipping layout. Copy the file next\n\
                to your binary and the program is deployable.\n\
             2. **`{native_half}`** — where this build put it, which is what makes\n\
                `cargo test` work right after `kirac build` with no ceremony. Last,\n\
                because it is the entry that stops being true the moment anything is\n\
                copied anywhere.\n\
             \n\
             A load that finds none of them fails with an error naming **every** path it\n\
             tried, so a missing native half says which places were looked in rather\n\
             than just that something was not found.\n",
            library = model.library,
            native_file = kira_hybrid_main::shared_library_file_name(&model.library),
            variable = kira_hybrid_main::override_variable(&model.library),
        ),
    }
}

/// Renders the generated crate's `README.md`, for either VM-family engine.
pub(crate) fn readme(model: &Model) -> String {
    let mut out = format!(
        "# {library}\n\
         \n\
         Generated by {built_by} from the Kira library `{library}`. **Do not\n\
         edit, and do not commit**: every build of the library rewrites this\n\
         directory, and the dependency paths in `Cargo.toml` are true only of the\n\
         Kira checkout that produced it.\n\
         \n\
         {what_this_is}\n\
         ## Using it\n\
         \n\
         ```toml\n\
         [dependencies]\n\
         {library} = {{ path = \"../{library}/.kira-build/rust/{library}\" }}\n\
         ```\n\
         \n\
         ```rust,ignore\n\
         let library = {ty}::load()?;\n\
         ```\n\
         \n\
         `load` checks the embedded bytecode against the surface this crate was\n\
         generated from and names the first export that disagrees, so a stale\n\
         wrapper fails at load rather than by calling the wrong function.\n\
         \n\
         ### Where the library's output goes\n\
         \n\
         `load()` sends the library's `print` to this process's stdout. To send it\n\
         somewhere else — a log, a test buffer, a browser console — supply a host:\n\
         \n\
         ```rust,ignore\n\
         let library = {ty}::load_with(my_host)?;\n\
         library.with_host(|host| /* read what it collected */);\n\
         ```\n\
         \n\
         A host is anything implementing `kira_runtime_abi::HostCapabilities`;\n\
         `CapturingHost` in that crate records every line and is what the tests use.\n\
         `{ty}` and each handle type are generic over it, defaulting to\n\
         `StdoutHost`, so nothing needs a type annotation until you supply one.\n\
         \n\
         ## What it promises\n\
         \n\
         - **One thread.** `{ty}` is neither `Send` nor `Sync`. One instance belongs\n\
           to one thread.\n\
         - **Handles are owned.** A value of an exported class type names a live\n\
           object inside the library. Dropping it releases that object, and nothing\n\
           else does.\n\
         - **Arguments are lent, results are owned.** A `&str` argument is copied\n\
           into the library for the call; a `String` result is yours.\n\
         \n",
        library = model.library,
        ty = model.library_type,
        built_by = built_by(&model.engine),
        what_this_is = what_this_is(model),
    );

    if let EngineBinding::Hybrid { .. } = model.engine {
        out.push_str(
            "- **`libloading` is in your dependency graph.** Opening the native half\n\
             \x20 means linking a dynamic loader. The VM engine (`kirac build`) needs\n\
             \x20 none, and is the default for that reason.\n\
             - **This crate does not build for `wasm32-unknown-unknown`.** Dynamic\n\
             \x20 loading has no meaning there. Build the library with `kirac build`\n\
             \x20 instead: the VM engine's crate is the wasm answer, and the consumer\n\
             \x20 code above is unchanged.\n\
             \n",
        );
    }

    out.push_str("## The surface\n\n");
    if model.functions.is_empty() {
        out.push_str("This library exports no functions.\n");
    } else {
        out.push_str("| Kira | Rust |\n|---|---|\n");
        for function in &model.functions {
            out.push_str(&format!(
                "| `{}` | `{}::{}` |\n",
                function.kira_name, model.library_type, function.method
            ));
        }
    }
    if !model.classes.is_empty() {
        out.push_str("\nExported classes, each a Rust newtype over a handle: ");
        let names: Vec<String> = model
            .classes
            .iter()
            .map(|class| format!("`{}`", class.rust))
            .collect();
        out.push_str(&names.join(", "));
        out.push_str(".\n");
    }
    out
}
