[package]
name = "kira-ksl-semantics"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
kira-source.workspace = true
kira-diagnostics.workspace = true
kira-ksl-syntax-model.workspace = true
kira-ksl-parser.workspace = true
kira-shader-model.workspace = true
kira-shader-ir.workspace = true
