[package]
name = "kira-main"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
kira-bytecode.workspace = true
kira-runtime-abi.workspace = true
kira-vm-runtime.workspace = true
thiserror.workspace = true

[lints]
workspace = true
