//! Native helper-thread/main-thread event-loop support.
//!
//! The generated native entry keeps the process's original thread as the
//! event-loop thread and runs Kira's `@Main` body on a helper. Main-thread
//! requests transfer `BridgeValue`s through a synchronized queue. The target
//! dispatcher is generated by the LLVM backend, so this runtime never knows
//! Kira function signatures or compiler internals.

use std::collections::{HashMap, VecDeque};
use std::sync::mpsc::{Sender, channel};
use std::sync::{Arc, Condvar, Mutex, OnceLock};
use std::thread::{self, ThreadId};

use kira_runtime_abi::{BridgeValue, BridgeValueTag, MainThreadOp};

mod fiber;

/// The generated dispatcher that enters one native or hybrid target.
///
/// # Safety
/// `args` points to `count` writable bridge values and `out` points to one
/// writable bridge value. The generated dispatcher validates the function id
/// against the module it was built from.
pub type MainThreadDispatcher =
    unsafe extern "C" fn(function: u32, args: *mut BridgeValue, count: u32, out: *mut BridgeValue);

/// Resolves a lifecycle function id to its generated zero-argument body.
pub type MainThreadLifecycleResolver = unsafe extern "C" fn(function: u32) -> *mut std::ffi::c_void;

/// A generated native entry function run on the helper thread.
pub type MainThreadEntry = extern "C" fn() -> i32;

/// One request waiting for the main thread.
struct Request {
    operation: MainThreadOp,
    function: u32,
    args: Vec<BridgeValue>,
}

/// A message from a helper thread.
enum Job {
    /// A new invoke, spawn, or post request.
    Request {
        /// The request payload.
        request: Request,
        /// The response channel.
        reply: Sender<Result<BridgeValue, String>>,
    },
    /// A task join request.
    Join {
        /// The task handle.
        handle: u64,
        /// The response channel.
        reply: Sender<Result<BridgeValue, String>>,
    },
}

/// One unit the caller's main-thread loop can execute.
enum Work {
    /// No queued message; advance the next lifecycle slice immediately.
    LifecycleTurn,
    /// A message from the helper.
    Job(Job),
    /// A fire-and-forget post that was already acknowledged.
    Post(Request),
    /// A spawned task selected for execution.
    Task {
        /// The task handle whose state receives the result.
        handle: u64,
        /// The task request.
        request: Request,
    },
}

/// A spawned task owned by the main-thread loop.
enum Task {
    /// The target has not run.
    Queued(Request),
    /// The target result is waiting for a join.
    Finished(Result<BridgeValue, String>),
}

/// Mutable state for one process main-thread run.
struct State {
    /// The thread that owns the event loop.
    main_thread: ThreadId,
    /// Requests arriving from helper threads.
    jobs: VecDeque<Job>,
    /// Fire-and-forget posts waiting for a main-thread turn.
    posts: VecDeque<Request>,
    /// Spawned tasks, keyed by a non-zero handle.
    tasks: HashMap<u64, Task>,
    /// The next handle; never reused during one runtime scope.
    next_handle: u64,
    /// The next helper entry result, once it returns.
    helper_result: Option<i32>,
    /// The first deferred failure, if a post or unjoined task failed.
    deferred_error: Option<String>,
}

/// The synchronized runtime shared by the helper and main threads.
struct Runtime {
    state: Mutex<State>,
    wake: Condvar,
}

static ACTIVE_RUNTIME: OnceLock<Mutex<Option<Arc<Runtime>>>> = OnceLock::new();
static DISPATCHER: OnceLock<Mutex<Option<MainThreadDispatcher>>> = OnceLock::new();
static LIFECYCLE_RESOLVER: OnceLock<Mutex<Option<MainThreadLifecycleResolver>>> = OnceLock::new();

/// Checkpoints one lifecycle may cross before another main-thread turn.
const LIFECYCLE_SLICE: u64 = 4096;

fn active_runtime_slot() -> &'static Mutex<Option<Arc<Runtime>>> {
    ACTIVE_RUNTIME.get_or_init(|| Mutex::new(None))
}

fn dispatcher_slot() -> &'static Mutex<Option<MainThreadDispatcher>> {
    DISPATCHER.get_or_init(|| Mutex::new(None))
}

fn lifecycle_resolver_slot() -> &'static Mutex<Option<MainThreadLifecycleResolver>> {
    LIFECYCLE_RESOLVER.get_or_init(|| Mutex::new(None))
}

fn lock<T>(mutex: &Mutex<T>) -> std::sync::MutexGuard<'_, T> {
    mutex
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
}

fn active_runtime() -> Option<Arc<Runtime>> {
    lock(active_runtime_slot()).clone()
}

fn dispatcher() -> Option<MainThreadDispatcher> {
    *lock(dispatcher_slot())
}

fn lifecycle_resolver() -> Option<MainThreadLifecycleResolver> {
    *lock(lifecycle_resolver_slot())
}

/// Installs the generated dispatcher used by main-thread calls.
///
/// The generated function pointer is process-local and remains valid for the
/// native run. Passing a null pointer clears the previous dispatcher.
///
/// # Safety
/// A non-null `pointer` must address a function with the
/// [`MainThreadDispatcher`] ABI and remain valid until replaced or cleared.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn kira_rt_main_thread_install_dispatcher(pointer: *mut std::ffi::c_void) {
    let value = if pointer.is_null() {
        None
    } else {
        // SAFETY: the backend passes the address of a function with exactly the
        // `MainThreadDispatcher` C ABI; the null case above is handled first.
        Some(unsafe { std::mem::transmute::<*mut std::ffi::c_void, MainThreadDispatcher>(pointer) })
    };
    *lock(dispatcher_slot()) = value;
}

/// Installs the generated lifecycle body resolver for this native image.
///
/// # Safety
/// A non-null `pointer` must address a function with exactly the
/// [`MainThreadLifecycleResolver`] ABI and remain live for the current run.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn kira_rt_main_thread_install_lifecycle_resolver(
    pointer: *mut std::ffi::c_void,
) {
    let value = if pointer.is_null() {
        None
    } else {
        // SAFETY: generated code passes the address of the resolver with this
        // exact C ABI, and the null case is handled above.
        Some(unsafe {
            std::mem::transmute::<*mut std::ffi::c_void, MainThreadLifecycleResolver>(pointer)
        })
    };
    *lock(lifecycle_resolver_slot()) = value;
}

/// Runs `entry` on a helper thread while the caller services main-thread work.
#[unsafe(no_mangle)]
pub extern "C" fn kira_rt_main_thread_run(entry: MainThreadEntry) -> i32 {
    fiber::reset();
    let runtime = Arc::new(Runtime {
        state: Mutex::new(State {
            main_thread: thread::current().id(),
            jobs: VecDeque::new(),
            posts: VecDeque::new(),
            tasks: HashMap::new(),
            next_handle: 1,
            helper_result: None,
            deferred_error: None,
        }),
        wake: Condvar::new(),
    });
    {
        let mut active = lock(active_runtime_slot());
        if active.is_some() {
            fatal("a main-thread runtime is already running");
        }
        *active = Some(Arc::clone(&runtime));
    }

    let helper_runtime = Arc::clone(&runtime);
    let helper = thread::Builder::new()
        .name("kira-helper".to_owned())
        .spawn(move || {
            let result = entry();
            let mut state = lock(&helper_runtime.state);
            state.helper_result = Some(result);
            helper_runtime.wake.notify_all();
        });
    let Ok(helper) = helper else {
        *lock(active_runtime_slot()) = None;
        fatal("could not start the Kira helper thread");
    };

    loop {
        fiber::pump(LIFECYCLE_SLICE);
        let work = {
            let mut state = lock(&runtime.state);
            loop {
                if let Some(request) = state.posts.pop_front() {
                    break Some(Work::Post(request));
                }
                if let Some(handle) = state
                    .tasks
                    .iter()
                    .filter_map(|(handle, task)| matches!(task, Task::Queued(_)).then_some(*handle))
                    .min_by_key(|handle| *handle)
                {
                    let Some(Task::Queued(request)) = state.tasks.remove(&handle) else {
                        continue;
                    };
                    break Some(Work::Task { handle, request });
                }
                if let Some(job) = state.jobs.pop_front() {
                    break Some(Work::Job(job));
                }
                if state.helper_result.is_some() && !fiber::active() {
                    break None;
                }
                if fiber::active() {
                    break Some(Work::LifecycleTurn);
                }
                state = runtime
                    .wake
                    .wait(state)
                    .unwrap_or_else(|poisoned| poisoned.into_inner());
            }
        };
        let Some(work) = work else {
            break;
        };
        runtime.service(work);
    }

    // All requests from the helper are complete. The remaining queued work is
    // still part of the program's requested main-thread side effects, so drain
    // it before allowing the runtime to leave its event loop.
    loop {
        let work = {
            let mut state = lock(&runtime.state);
            if let Some(request) = state.posts.pop_front() {
                Some(Work::Post(request))
            } else if let Some(handle) = state
                .tasks
                .iter()
                .filter_map(|(handle, task)| matches!(task, Task::Queued(_)).then_some(*handle))
                .min_by_key(|handle| *handle)
            {
                match state.tasks.remove(&handle) {
                    Some(Task::Queued(request)) => Some(Work::Task { handle, request }),
                    _ => None,
                }
            } else {
                None
            }
        };
        let Some(work) = work else {
            break;
        };
        runtime.service(work);
    }

    let result = lock(&runtime.state).helper_result.unwrap_or(1);
    let remaining = {
        let mut state = lock(&runtime.state);
        state
            .tasks
            .drain()
            .map(|(_, task)| task)
            .collect::<Vec<_>>()
    };
    for task in remaining {
        match task {
            Task::Finished(Ok(value)) => discard(value),
            Task::Finished(Err(error)) => deferred_failure(&runtime, error),
            Task::Queued(_) => {}
        }
    }
    let deferred_error = lock(&runtime.state).deferred_error.clone();
    if let Err(error) = helper.join() {
        let _ = error;
        fatal("the Kira helper thread panicked");
    }
    *lock(active_runtime_slot()) = None;
    fiber::reset();
    if let Some(error) = deferred_error {
        eprintln!("kira: runtime trap: main-thread function failed: {error}");
        1
    } else {
        result
    }
}

impl Runtime {
    /// Services one helper message on the main thread.
    fn service(self: &Arc<Self>, work: Work) {
        match work {
            Work::LifecycleTurn => {}
            Work::Post(request) => match self.dispatch(request) {
                Ok(value) => discard(value),
                Err(error) => deferred_failure(self, error),
            },
            Work::Task { handle, request } => {
                let result = self.dispatch(request);
                if let Err(error) = &result {
                    deferred_failure(self, error.clone());
                }
                lock(&self.state)
                    .tasks
                    .insert(handle, Task::Finished(result));
            }
            Work::Job(job) => match job {
                Job::Request { request, reply } => match request.operation {
                    MainThreadOp::Invoke => {
                        let result = self.dispatch(request);
                        let _ = reply.send(result);
                    }
                    MainThreadOp::Spawn => {
                        let handle = self.allocate_handle(request);
                        let _ = reply.send(Ok(BridgeValue::new(BridgeValueTag::HANDLE, handle)));
                    }
                    MainThreadOp::Post => {
                        let mut state = lock(&self.state);
                        state.posts.push_back(request);
                        let _ = reply.send(Ok(BridgeValue::VOID));
                        self.wake.notify_all();
                    }
                    MainThreadOp::LifecycleStart => {
                        let result = self
                            .start_lifecycle_on_owner(request.function)
                            .map(|()| BridgeValue::VOID);
                        let _ = reply.send(result);
                    }
                },
                Job::Join { handle, reply } => {
                    let result = self.join(handle);
                    let _ = reply.send(result);
                }
            },
        }
    }

    /// Resolves and registers one lifecycle body on the current main thread.
    fn start_lifecycle_on_owner(&self, function: u32) -> Result<(), String> {
        if thread::current().id() != lock(&self.state).main_thread {
            return Err("a lifecycle was started away from the main thread".to_owned());
        }
        start_lifecycle(function)
    }

    /// Adds a queued task and returns its non-zero handle.
    fn allocate_handle(&self, request: Request) -> u64 {
        let mut state = lock(&self.state);
        let handle = state.next_handle;
        state.next_handle = state
            .next_handle
            .checked_add(1)
            .unwrap_or_else(|| fatal("main-thread task handle space exhausted"));
        state.tasks.insert(handle, Task::Queued(request));
        handle
    }

    /// Executes a task if needed and returns its result, translating `Void` to
    /// the integer zero convention used by the Kira task surface.
    fn join(&self, handle: u64) -> Result<BridgeValue, String> {
        let task = lock(&self.state).tasks.remove(&handle);
        let result = match task {
            Some(Task::Queued(request)) => self.dispatch(request),
            Some(Task::Finished(result)) => result,
            None => return Err(format!("main-thread task handle {handle} is unknown")),
        }?;
        if result.tag == BridgeValueTag::VOID {
            Ok(BridgeValue::encode(kira_runtime_abi::BridgeData::Int(0)))
        } else {
            Ok(result)
        }
    }

    /// Calls the generated dispatcher on this thread.
    fn dispatch(&self, mut request: Request) -> Result<BridgeValue, String> {
        let Some(dispatcher) = dispatcher() else {
            return Err("no main-thread dispatcher is installed".to_owned());
        };
        let mut output = BridgeValue::VOID;
        let count = u32::try_from(request.args.len())
            .map_err(|_| "main-thread argument list is too large".to_owned())?;
        let args = if request.args.is_empty() {
            std::ptr::null_mut()
        } else {
            request.args.as_mut_ptr()
        };
        // SAFETY: the request owns `args` for the duration of this call, the
        // dispatcher came from the generated module, and `output` is writable.
        unsafe { dispatcher(request.function, args, count, &mut output) };
        Ok(output)
    }
}

fn start_lifecycle(function: u32) -> Result<(), String> {
    let resolver = lifecycle_resolver()
        .ok_or_else(|| "no main-thread lifecycle resolver is installed".to_owned())?;
    // SAFETY: the resolver belongs to the generated image active for this run
    // and returns null for a lifecycle body it does not carry.
    let pointer = unsafe { resolver(function) };
    if pointer.is_null() {
        return Err(format!(
            "main-thread lifecycle function {function} is unknown"
        ));
    }
    // SAFETY: every non-null resolver result is a generated zero-argument
    // lifecycle function in the same loaded image.
    let entry =
        unsafe { std::mem::transmute::<*mut std::ffi::c_void, fiber::LifecycleEntry>(pointer) };
    fiber::start(entry).map_err(str::to_owned)
}

/// Starts a lifecycle directly from a host loop already on the main thread.
#[unsafe(no_mangle)]
pub extern "C" fn kira_rt_main_thread_lifecycle_start_local(function: u32) -> u8 {
    u8::from(start_lifecycle(function).is_ok())
}

/// Advances every locally scheduled native lifecycle by one slice.
#[unsafe(no_mangle)]
pub extern "C" fn kira_rt_main_thread_lifecycle_pump_local(budget: u64) -> u8 {
    u8::from(fiber::pump(budget))
}

/// Clears locally scheduled lifecycle stacks at a host-run boundary.
#[unsafe(no_mangle)]
pub extern "C" fn kira_rt_main_thread_lifecycle_reset_local() {
    fiber::reset();
}

/// Sends a main-thread request and writes its bridge result to `out`.
///
/// # Safety
/// `out` must point to one writable [`BridgeValue`]. When `count` is positive,
/// `args` must point to `count` initialized bridge values.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn kira_rt_main_thread_call(
    operation: i64,
    function: i32,
    args: *mut BridgeValue,
    count: i32,
    out: *mut BridgeValue,
) {
    if out.is_null() {
        fatal("main-thread call received a null output slot");
    }
    let operation = u8::try_from(operation)
        .ok()
        .and_then(MainThreadOp::from_byte)
        .unwrap_or_else(|| fatal("main-thread call received an unknown operation"));
    let function =
        u32::try_from(function).unwrap_or_else(|_| fatal("main-thread function id is negative"));
    let count =
        usize::try_from(count).unwrap_or_else(|_| fatal("main-thread argument count is negative"));
    let values = if count == 0 {
        Vec::new()
    } else if args.is_null() {
        fatal("main-thread call received null arguments");
    } else {
        // SAFETY: the generated caller passes `count` initialized bridge values.
        unsafe { std::slice::from_raw_parts(args, count).to_vec() }
    };
    let request = Request {
        operation,
        function,
        args: values,
    };
    let Some(runtime) = active_runtime() else {
        fatal("main-thread call happened outside a main-thread runtime");
    };
    let result = if thread::current().id() == lock(&runtime.state).main_thread {
        let (reply, receiver) = channel();
        runtime.service(Work::Job(Job::Request { request, reply }));
        receiver
            .recv()
            .unwrap_or_else(|_| Err("main-thread response was dropped".to_owned()))
    } else {
        let (reply, receiver) = channel();
        {
            let mut state = lock(&runtime.state);
            state.jobs.push_back(Job::Request { request, reply });
        }
        runtime.wake.notify_all();
        receiver
            .recv()
            .unwrap_or_else(|_| Err("main-thread response was dropped".to_owned()))
    };
    let value = result.unwrap_or_else(|error| fatal(&error));
    // SAFETY: the caller gave one writable bridge-value output slot.
    unsafe { *out = value };
}

/// Joins a task returned by `MainThread.spawn`.
///
/// # Safety
/// `out` must point to one writable [`BridgeValue`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn kira_rt_main_thread_join(handle: i64, out: *mut BridgeValue) {
    if out.is_null() {
        fatal("main-thread join received a null output slot");
    }
    let handle =
        u64::try_from(handle).unwrap_or_else(|_| fatal("main-thread task handle is negative"));
    let Some(runtime) = active_runtime() else {
        fatal("main-thread join happened outside a main-thread runtime");
    };
    let value = if thread::current().id() == lock(&runtime.state).main_thread {
        runtime.join(handle).unwrap_or_else(|error| fatal(&error))
    } else {
        let (reply, receiver) = channel();
        {
            let mut state = lock(&runtime.state);
            state.jobs.push_back(Job::Join { handle, reply });
        }
        runtime.wake.notify_all();
        receiver
            .recv()
            .unwrap_or_else(|_| Err("main-thread join response was dropped".to_owned()))
            .unwrap_or_else(|error| fatal(&error))
    };
    // SAFETY: the caller gave one writable bridge-value output slot.
    unsafe { *out = value };
}

/// Drops an output bridge value that a post does not return to Kira.
fn discard(value: BridgeValue) {
    match value.tag {
        BridgeValueTag::STRING => {
            // SAFETY: the dispatcher produced this live string handle and the
            // post owns the only result copy.
            unsafe {
                crate::runtime::kira_rt_str_free(value.payload as *mut crate::runtime::KiraString)
            };
        }
        BridgeValueTag::NODE | BridgeValueTag::ANY => {
            // SAFETY: the dispatcher produced this live native-value node and
            // the post owns it after the dispatcher returned.
            unsafe {
                crate::native_state::kira_rt_native_value_free(
                    value.payload as crate::native_state::KNativeStateValue,
                )
            };
        }
        _ => {}
    }
}

/// Records a deferred failure without interrupting the helper thread.
fn deferred_failure(runtime: &Arc<Runtime>, error: String) {
    let mut state = lock(&runtime.state);
    state.deferred_error.get_or_insert(error);
}

/// Terminates native execution with a main-thread runtime trap.
fn fatal(message: &str) -> ! {
    eprintln!("kira: runtime trap: {message}");
    std::process::exit(1)
}

#[cfg(all(test, not(target_family = "wasm")))]
mod tests {
    use super::*;
    use kira_runtime_abi::{BridgeData, MainThreadOp};
    use std::sync::atomic::{AtomicBool, Ordering};

    static THREADS: OnceLock<Mutex<Vec<ThreadId>>> = OnceLock::new();
    static VALUES: OnceLock<Mutex<Vec<i64>>> = OnceLock::new();
    static FAILURE: AtomicBool = AtomicBool::new(false);
    static TEST_LOCK: Mutex<()> = Mutex::new(());

    fn threads() -> &'static Mutex<Vec<ThreadId>> {
        THREADS.get_or_init(|| Mutex::new(Vec::new()))
    }

    fn values() -> &'static Mutex<Vec<i64>> {
        VALUES.get_or_init(|| Mutex::new(Vec::new()))
    }

    fn record(value: i64) {
        lock(threads()).push(thread::current().id());
        lock(values()).push(value);
    }

    /// The generated dispatcher shape used by the native runtime test.
    unsafe extern "C" fn dispatch(
        function: u32,
        args: *mut BridgeValue,
        count: u32,
        out: *mut BridgeValue,
    ) {
        if out.is_null() || count != 1 || args.is_null() {
            FAILURE.store(true, Ordering::Relaxed);
            return;
        }
        // SAFETY: this test's entry always passes one initialized value and one
        // writable output slot, which is the dispatcher contract.
        let value = unsafe { (*args).payload as i64 };
        record(value);
        // SAFETY: `out` is checked non-null above and belongs to the caller.
        unsafe {
            *out = BridgeValue::encode(BridgeData::Int(value + i64::from(function)));
        }
    }

    /// Enters one spawn, one post, and one join through the C ABI.
    extern "C" fn entry() -> i32 {
        record(-1);
        let mut argument = [BridgeValue::encode(BridgeData::Int(10))];
        let mut spawned = BridgeValue::VOID;
        // SAFETY: the runtime owns the active scope, `argument` has one live
        // bridge value, and `spawned` is one writable output slot.
        unsafe {
            kira_rt_main_thread_call(
                i64::from(MainThreadOp::Spawn.as_byte()),
                1,
                argument.as_mut_ptr(),
                1,
                &mut spawned,
            );
        }
        let handle = spawned.payload as i64;
        argument[0] = BridgeValue::encode(BridgeData::Int(20));
        let mut posted = BridgeValue::VOID;
        // SAFETY: the same owned argument/output contract as the spawn call.
        unsafe {
            kira_rt_main_thread_call(
                i64::from(MainThreadOp::Post.as_byte()),
                2,
                argument.as_mut_ptr(),
                1,
                &mut posted,
            );
        }
        let mut joined = BridgeValue::VOID;
        // SAFETY: `handle` came from the active runtime's spawn response and
        // `joined` is one writable output slot.
        unsafe { kira_rt_main_thread_join(handle, &mut joined) };
        record(joined.payload as i64);
        if joined.payload as i64 == 11 { 0 } else { 1 }
    }

    #[test]
    fn native_runtime_keeps_requests_on_the_process_main_thread() {
        let _guard = TEST_LOCK
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        FAILURE.store(false, Ordering::Relaxed);
        lock(threads()).clear();
        lock(values()).clear();
        // SAFETY: `dispatch` has the exact generated C dispatcher ABI, and the
        // runtime reads it only during this test's active scope.
        unsafe {
            kira_rt_main_thread_install_dispatcher(dispatch as *mut std::ffi::c_void);
        }
        let status = kira_rt_main_thread_run(entry);
        // SAFETY: clearing the process-local test dispatcher prevents a later
        // test or embedder from calling into this test module.
        unsafe { kira_rt_main_thread_install_dispatcher(std::ptr::null_mut()) };

        let threads = lock(threads()).clone();
        let values = lock(values()).clone();
        assert_eq!(status, 0);
        assert!(!FAILURE.load(Ordering::Relaxed));
        assert_eq!(values, [-1, 10, 20, 11]);
        assert_eq!(threads[0], threads[3]);
        assert_ne!(threads[0], threads[1]);
        assert_eq!(threads[1], threads[2]);
    }
}
