[package]
name = "kira-hybrid-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
kira-core.workspace = true
kira-runtime-abi.workspace = true
kira-hybrid-definition.workspace = true
kira-native-bridge.workspace = true
kira-vm-runtime.workspace = true
kira-bytecode.workspace = true
