//! The Web export's host page, browser FFI surface, and artifact manifest.
//!
//! Three files turn a linked wasm module into something a browser runs: the
//! page that loads it, the generated FFI bridge the module's DOM and timer
//! imports resolve against, and a machine-readable manifest saying what was
//! built. All three are pure text over the build's facts — project name,
//! surface, file names — so they are tested against their own output and the
//! CLI only decides *what* was built.
//!
//! The page deliberately pre-defines emscripten's `Module` object before the
//! loader script runs, so stdout arrives through `Module.print` and lifecycle
//! events through `onRuntimeInitialized`/`postRun` — real callbacks from the
//! real runtime, never synthesized markers.

use crate::{ExportedFile, GeneratedProject};

/// The names every consumer of the export can rely on.
///
/// The loader and module are copied to these canonical names beside their
/// original-named originals (emscripten bakes the original stem into its
/// fetch path), so both spellings always resolve.
pub const PAGE_FILE: &str = "index.html";
pub const BROWSER_FFI_FILE: &str = "kira-browser-ffi.generated.js";
pub const MANIFEST_FILE: &str = "manifest.json";
pub const LOADER_FILE: &str = "main.js";
pub const MODULE_FILE: &str = "main.wasm";

/// The host page for `project_name` running `module_file`.
pub fn index_html(project_name: &str, surface_label: &str) -> String {
    format!(
        r#"<!doctype html>
<html><head><meta charset="utf-8"><title>{project_name}</title></head>
<body data-kira-runner="web" data-kira-surface="{surface_label}" data-kira-artifact="{MODULE_FILE}">
<h1>{project_name}</h1>
<pre id="kira-stdout" aria-label="Kira application output"></pre>
<script src="./{BROWSER_FFI_FILE}"></script>
<script>
(() => {{
  const sink = document.getElementById("kira-stdout");
  const emit = (line) => {{ if (sink) sink.textContent += line + "\n"; console.log(line); }};
  const appOut = (text) => {{ if (sink) sink.textContent += text + "\n"; console.log(text); }};
  globalThis.KiraWasmApp = {{ moduleLoaded: false, runtimeStarted: false, mainReturned: false, stdout: [] }};
  globalThis.Module = {{
    print: (text) => {{ globalThis.KiraWasmApp.stdout.push(text); appOut(text); }},
    printErr: (text) => {{ console.error(text); }},
    onRuntimeInitialized: () => {{
      globalThis.KiraWasmApp.moduleLoaded = true;
      globalThis.KiraWasmApp.runtimeStarted = true;
      emit("kira.wasm.module_loaded");
      emit("kira.runtime.started");
    }},
    postRun: [() => {{
      globalThis.KiraWasmApp.mainReturned = true;
      emit("kira.app.main_returned");
    }}],
  }};
}})();
</script>
<script src="./{LOADER_FILE}"></script>
</body></html>
"#
    )
}

/// The generated browser-FFI bridge: the callbacks, timers, and DOM bindings
/// the module's `@FFI` imports resolve against at run time.
///
/// Generated rather than hand-written because it is a *surface*: the symbol
/// names here are what foreign adapters reference, so they are pinned by test
/// exactly like any other ABI.
pub fn browser_ffi_js() -> &'static str {
    "// generated by Kira Foundation.Web FFI binding generator
(() => {
  const callbacks = new Map();
  let nextCallbackId = 1;
  const timers = new Map();

  globalThis.KiraBrowserCallbackRegistry = {
    register(callback) {
      const id = nextCallbackId++;
      callbacks.set(id, callback);
      return id;
    },
    invoke(id, ...args) {
      const callback = callbacks.get(id);
      if (!callback) throw new Error(`kira: no callback ${id}`);
      return callback(...args);
    },
    remove(id) { return callbacks.delete(id); },
    clearAll() { callbacks.clear(); },
    activeCount() { return callbacks.size; },
    setTimer(ms, callback) {
      const id = globalThis.setTimeout(() => { timers.delete(id); callback(); }, ms);
      timers.set(id, true);
      return id;
    },
    clearTimer(id) {
      globalThis.clearTimeout(id);
      timers.delete(id);
    },
  };

  const registry = () => globalThis.KiraBrowserCallbackRegistry;

  globalThis.KiraBrowserFFI = {
    documentBody() { return document.body; },
    createElement(tag) { return document.createElement(tag); },
    setText(node, text) { node.textContent = text; },
    appendChild(parent, child) { parent.appendChild(child); },
    setAttribute(node, name, value) { node.setAttribute(name, value); },
    setStyle(node, name, value) { node.style.setProperty(name, value); },
    addClass(node, name) { node.classList.add(name); },
    removeClass(node, name) { node.classList.remove(name); },
    registerCallback(callback) { return registry().register(callback); },
    invokeCallback(id, ...args) { return registry().invoke(id, ...args); },
    removeCallback(id) { return registry().remove(id); },
    clearCallbacks() { registry().clearAll(); },
    activeCallbackCount() { return registry().activeCount(); },
    addEventListener(target, event, id) {
      target.addEventListener(event, (e) => registry().invoke(id, e.type));
    },
    removeEventListener(target, event, handler) {
      target.removeEventListener(event, handler);
    },
    onClick(target, id) {
      target.addEventListener('click', () => registry().invoke(id));
    },
    consoleLog(text) { console.log(text); },
    userAgent() { return navigator.userAgent; },
    href() { return globalThis.location.href; },
    setTimeout(ms, id) { return registry().setTimer(ms, () => registry().invoke(id)); },
    clearTimeout(handle) { registry().clearTimer(handle); },
    createCanvas(width, height) {
      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      document.body.appendChild(canvas);
      return canvas;
    },
    async detectWebGPU() {
      if (!navigator.gpu) return { available: false, adapter: null };
      const adapter = await navigator.gpu.requestAdapter();
      return { available: true, adapter };
    },
  };
})();
"
}

/// One field of the export manifest, rendered as JSON text.
struct ManifestFields<'a> {
    project_name: &'a str,
    surface: &'a str,
    rendering_model: &'a str,
    graphics_capability: Option<&'static str>,
    requires_canvas: bool,
    requires_browser_detection: bool,
}

/// Renders the JSON manifest describing what this export contains.
///
/// Hand-rendered rather than through a JSON library because it is one flat
/// object of known fields whose exact bytes are part of the generator's test:
/// a serializer would buy escaping nothing needs and cost the pinning.
fn manifest_json(fields: &ManifestFields<'_>) -> String {
    // Values are all toolchain-controlled identifiers with no quoting needs;
    // the app name is the one caller-supplied string, and a quote in it would
    // be a package-name problem that shows up in every artifact name long
    // before it reaches this line.
    format!(
        "{{\"runner\":\"web\",\"runtime\":\"kira-wasm\",\"artifact\":\"{module}\",\"loader\":\"{loader}\",\"artifact_kind\":\"emscripten-compiled-app\",\"placeholder\":false,\"surface\":\"{surface}\",\"rendering_model\":\"{rendering}\",\"graphics_capability\":{capability},\"requires_canvas\":{canvas},\"requires_browser_detection\":{browser},\"app\":\"{app}\"}}\n",
        module = MODULE_FILE,
        loader = LOADER_FILE,
        surface = fields.surface,
        rendering = fields.rendering_model,
        capability = match fields.graphics_capability {
            Some(name) => format!("\"{name}\""),
            None => "null".to_owned(),
        },
        canvas = fields.requires_canvas,
        browser = fields.requires_browser_detection,
        app = fields.project_name,
    )
}

/// Every generated file of a Web export: the page, the FFI bridge, and the
/// manifest. The loader and module themselves are build artifacts — the CLI
/// copies them in under [`LOADER_FILE`] and [`MODULE_FILE`].
pub fn web_project(
    project_name: &str,
    surface: kira_manifest::platform_config::WebSurfaceRequirements,
) -> GeneratedProject {
    use kira_manifest::platform_config::WebRenderingModel;

    let rendering_model = match surface.rendering_model {
        WebRenderingModel::Dom => "dom",
        WebRenderingModel::GraphicsCanvas => "graphics-canvas",
        WebRenderingModel::Hybrid => "hybrid",
    };
    let json = manifest_json(&ManifestFields {
        project_name,
        surface: surface.surface.label(),
        rendering_model,
        graphics_capability: surface
            .graphics_capability
            .map(|capability| capability.label()),
        requires_canvas: surface.requires_canvas,
        requires_browser_detection: surface.requires_browser_detection,
    });
    GeneratedProject {
        files: vec![
            ExportedFile::new(PAGE_FILE, index_html(project_name, surface.surface.label())),
            ExportedFile::new(BROWSER_FFI_FILE, browser_ffi_js()),
            ExportedFile::new(MANIFEST_FILE, json),
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use kira_manifest::platform_config::{WebSurface, web_surface_requirements};

    #[test]
    fn the_page_wires_the_real_runtime_callbacks_to_stdout() {
        let page = index_html("Demo", "dom");
        assert!(page.contains("data-kira-runner=\"web\""));
        assert!(page.contains("data-kira-surface=\"dom\""));
        assert!(page.contains("data-kira-artifact=\"main.wasm\""));
        assert!(page.contains("<script src=\"./main.js\"></script>"));
        assert!(page.contains("<script src=\"./kira-browser-ffi.generated.js\"></script>"));
        assert!(page.contains("onRuntimeInitialized"));
        assert!(page.contains("emit(\"kira.wasm.module_loaded\")"));
        // Nothing is faked: no hardcoded success marker outside the two
        // lifecycle callbacks emscripten actually fires.
        assert!(!page.contains("kira.app.rendered"));
    }

    #[test]
    fn the_ffi_surface_names_every_binding_foreign_adapters_reference() {
        let ffi = browser_ffi_js();
        for symbol in [
            "KiraBrowserFFI",
            "KiraBrowserCallbackRegistry",
            "documentBody",
            "createCanvas",
            "detectWebGPU",
            "setTimeout",
            "registerCallback",
            "invokeCallback",
        ] {
            assert!(ffi.contains(symbol), "the bridge must expose `{symbol}`");
        }
    }

    #[test]
    fn dom_and_webgpu_manifests_differ_where_the_surfaces_differ() {
        let dom = web_project("Demo", web_surface_requirements(WebSurface::Dom));
        let webgpu = web_project("Demo", web_surface_requirements(WebSurface::Webgpu));

        let dom_json = json_of(&dom);
        assert!(dom_json.contains("\"rendering_model\":\"dom\""));
        assert!(dom_json.contains("\"requires_canvas\":false"));
        assert!(dom_json.contains("\"graphics_capability\":null"));

        let webgpu_json = json_of(&webgpu);
        assert!(webgpu_json.contains("\"rendering_model\":\"graphics-canvas\""));
        assert!(webgpu_json.contains("\"graphics_capability\":\"webgpu\""));
        assert!(webgpu_json.contains("\"requires_canvas\":true"));
        assert!(webgpu_json.contains("\"requires_browser_detection\":true"));
        assert!(json_of(&webgpu).contains("\"app\":\"Demo\""));
    }

    fn json_of(project: &GeneratedProject) -> String {
        project
            .files
            .iter()
            .find(|file| file.path == std::path::Path::new(MANIFEST_FILE))
            .expect("the manifest")
            .contents
            .clone()
    }
}
