[package]
name = "kira-program-graph"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kira-parser.workspace = true
kira-semantics.workspace = true
kira-source.workspace = true
kira-syntax-model.workspace = true
thiserror.workspace = true

[lints]
workspace = true
