//! A Rust program consuming a Kira library, built the way a real one would be.
//!
//! This crate is the end-to-end proof of the export feature's VM engine, and it
//! is deliberately not a mock of one. `build.rs` compiles the Kira library in
//! `fixture/uifoundation/` through the same frontend `kira` uses, generates the
//! same wrapper crate `kira build` writes, and this file compiles that
//! generated code under this workspace's own lint gate. The tests then call it:
//! `uifoundation::make_button("ok")`, a handle out, a string back, a handle
//! dropped and the object released.
//!
//! # What it proves that a unit test cannot
//!
//! - **The generated code compiles**, under `-D warnings`, with no `unsafe` and
//!   no `#[allow]`. A generator test can assert what was written; only a
//!   compiler can say it was Rust.
//! - **It runs on the CI machine**, with no LLVM, no linker, and no toolchain
//!   fetch. The VM engine's whole claim is that a consumer needs none of those,
//!   and this crate is where that claim is cashed.
//! - **It builds for `wasm32-unknown-unknown`**, which is this feature's honest
//!   wasm answer: a Rust wasm application embedding a Kira library. The done-bar
//!   runs `cargo check -p kira-export-consumer --target wasm32-unknown-unknown`.
//!
//! # How the generated crate gets in here
//!
//! By `include!` of the file `build.rs` generated into `OUT_DIR`, rather than by
//! a path dependency: cargo resolves dependencies before it runs build scripts,
//! so a path dependency on a directory that does not exist until something
//! builds it cannot work on a clean checkout. Including it is also the stricter
//! test — the generated code is compiled under *this* crate's lints rather than
//! its own.

/// The Kira library `uifoundation`, as generated by `kira`.
///
/// Everything in here is machine-written; see `fixture/uifoundation/` for the
/// Kira source it comes from.
pub mod uifoundation {
    include!(env!("KIRA_UIFOUNDATION_WRAPPER"));
}

/// The directory the wrapper crate was generated into.
///
/// Exposed so the tests can read what was written beside the source they
/// compile — the `Cargo.toml`, the `README.md`, the embedded artifact — and
/// check the parts a compiler has no opinion about.
pub const GENERATED_CRATE: &str = env!("KIRA_UIFOUNDATION_CRATE");
